name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World Parent Workflow!"
      
      - name: rahul-test-hello-action
        uses: jainrahul0311/RahulTestHelloAction@master

